### ISSUE TITLE
MPD audio/video download

### ISSUE THREAD

**Issue by jybp** [chris124567/hulu#1]
Would you be open to contributions that would add the MPD audio/video download part to the repository?
To basically remove the `yt-dlp` dependency?

Asking because of:
> Technically, this could be implemented rather easily in this repository but I want to keep this repository simple and avoid rewriting code to deal with segment merging or quality selection menus.

**Comment by chris124567** [comment]
Yeah certainly.  I just wanted the initial release to be simple.
