### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by B4U2D0** [chris124567/hulu#10]
Whether movie or tv show, same error. I can use the query command just fine, but not the download command.
```
panic: proto: cannot parse invalid wire-format data

goroutine 1 [running]:
main.main()
        /home/mantiqulla/hulu/main.go:172 +0x1c93
```

Edit: Using Ubuntu on windows; go version 1.16.12

Edit2: crap, I don't think I read through the dependencies good enough. looking into that now

Edit3: nope wasn't a bento problem

**Comment by chris124567** [comment]
Try again :) I just updated the private key with a new one

**Comment by B4U2D0** [comment]
Completely removed the directory, ran a git clone, cd'd into the directory, ran go build (not sure if that was necessary) Successfully ran a query, then hit the same error again when running the DL command.

I think if I tested it on an actual Linux box it would work. Probably has something to do with this WSL Ubuntu crap on Windows.

**Comment by chris124567** [comment]
```
$ HULU_SESSION="xxxxxxxx" go run . download -id="76187e1d-1bd0-491d-8c20-58146b1f0b3b"
```
```
MPD URL:  https://manifest-dp.hulustream.com/dash/61276064.mpd?xxxxxxxxxxxx
Decryption command:  mp4decrypt input.mp4 output.mp4 --key d34eba104dfc5b8caefe5dcb278a5d4b:5f68df92d0108d43941cc21708da7e92
```

Works here.  Very strange

**Comment by B4U2D0** [comment]
Just tested the exact same method I used in a kali VM and got the same error so I must be doing something wrong. 🤔 
I noticed you used a different syntax so I'll try that

**Comment by B4U2D0** [comment]
Yup US here too

**Comment by chris124567** [comment]
Bento4 and yt-dlp are not actually needed to run the Go program.  The Go program just gets the keys and links that you can provide to mp4decrypt and yt-dlp to retrieve and decrypt the mp4.

**Comment by B4U2D0** [comment]
Well crap. Then maybe i'm installing it wrong

**Comment by B4U2D0** [comment]
Well it is working for the most part given I can run search queries, just not the download command.

**Comment by B4U2D0** [comment]
![image](https://user-images.githubusercontent.com/20806827/147522055-d8e3a8a1-5bfc-4f2f-aed7-dc94e9898682.png)

**Comment by B4U2D0** [comment]
![image](https://user-images.githubusercontent.com/20806827/147522126-52529de6-d4b6-449c-ab88-6e76d197f3f4.png)

**Comment by chris124567** [comment]
Try adjusting [this line](https://github.com/chris124567/hulu/blob/master/client/types.go#L22) to the user agent of whatever browser you are signed into Hulu on.

**Comment by chris124567** [comment]
That happens to be my user agent but obviously everyone doesn't have the same setup as me.  I suspect it's Hulu/Widevine doing some kind of risk/fingerprint analysis to see what requests are legitimate.

**Comment by B4U2D0** [comment]
That was it. 🚀

**Comment by B4U2D0** [comment]
Awesome, thanks for the quick troubleshooting.

**Comment by chris124567** [comment]
I guess I'm gonna have to make the user agent customizable.  Thanks for finding this issue :+1:

**Comment by andoni10war** [comment]
How did you change the user agent?

I have try to change it in C:\Users\MyUser\go\pkg\mod\github.com\chris124567\hulu@v0.0.0-20211228022027-01066e973bd9\client\types.go and then I have executed go build in that path, but I am getting the same error.

What am I doing wrong?
