### ISSUE TITLE
panic: Get "": unsupported protocol scheme "" | panic: proto: cannot parse invalid wire-format data

### ISSUE THREAD

**Issue by azfirefighter** [chris124567/hulu#11]
When I attempt to run

HULU_SESSION="blah" hulu download -id="blah"

I alternately get one of the following two errors:
- panic: Get "": unsupported protocol scheme ""
- panic: proto: cannot parse invalid wire-format data

Which error depends on what movie ID I use.

EXACT ERROR MESSAGES
------------------------------------------------------

**panic: Get "": unsupported protocol scheme ""**

HULU_SESSION="REDACTED" ~/go/bin/hulu download -id="42f7eefe-2448-4ed5-87cb-6233c89c20f6"
panic: Get "": unsupported protocol scheme ""

goroutine 1 [running]:
main.main()
	/home/jake/go/pkg/mod/github.com/chris124567/hulu@v0.0.0-20211228022027-01066e973bd9/main.go:131 +0x1d05

------------------------------------------------------

**panic: proto: cannot parse invalid wire-format data**

HULU_SESSION="REDACTED" ~/go/bin/hulu download -id="fd311578-bbce-45f4-949f-8d62ebcec582"
panic: proto: cannot parse invalid wire-format data

goroutine 1 [running]:
main.main()
	/home/jake/go/pkg/mod/github.com/chris124567/hulu@v0.0.0-20211228022027-01066e973bd9/main.go:172 +0x1c93

------------------------------------------------------

Package version: latest
go version: 1.16
hulu is installed in ~/go/bin
Bento4 SDK is installed in ~/Bento4
yt-dlp is installed in ~

**Comment by chris124567** [comment]
Another day another key revocation.  Widevine is on a banning spree.  I'll look at this later today or tomorrow.  Happy new year :)

**Comment by azfirefighter** [comment]
Gotta love it. Enjoy your evening!

—-
Jason Todd
***@***.***
https://www.lltodd.family

On Dec 31, 2021, at 09:42, Christopher Tarry ***@***.***> wrote:

﻿

Another day another key revocation. Widevine is on a banning spree. I'll look at this later today or tomorrow. Happy new year :)

**Comment by asadboi123** [comment]
how can i use my own L3? I changed key in consts but how do i add the blob?

**Comment by chris124567** [comment]
@azfirefighter:
Tried some Sony, Lenovo, and Asus keys I found on Github but none worked.  I guess all of the leaked keys have been revoked.  I'll keep my eyes open for anything new but until then this program won't work.

@asadboi123:
ClientID is taken in the form of bytes.  The `DefaultClientID` variable is just a byte slice of all the bytes in the `device_client_id_blob` file.  Refer to https://pkg.go.dev/github.com/chris124567/hulu@v0.0.0-20211228022027-01066e973bd9/widevine#NewCDM.

You would do something like:
```
	// client := hulu.NewDefaultClient(huluSession, huluGUID)
	privateKey := `PRIVATE KEY`
	clientID, err := os.ReadFile("device_client_id_blob")
	if err != nil {
		panic(err)
	}
	client := hulu.NewCDM(privateKey, clientID, huluSession, huluGUID)
```
It'd be appreciated if you shared your key here.

**Comment by jkmartindale** [comment]
> It'd be appreciated if you shared your key here.

Doubt this will last long but enjoy https://github.com/widevinedump/L1-Give-Away

**Comment by asadboi123** [comment]
thanks i got it to work. i dumped the key from my phone using the L3 dumper, if i find an old phone i'll share. 

https://github.com/Xen0byte/Vinetrimmer-DRM-TOOL/blob/main/vinetrimmer/services/hulu.py

according to this, you can get UHD with L3, is this something you can look at?

**Comment by ShubuYeole12** [comment]
@asadboi123  how did u added the private key and client id and u explain plz.

**Comment by mrfrieza** [comment]
Same issue here, I followed the steps, had some issue (as I'm running it on Windows) but finally made it work, but had this "wire-format data" message as well ^^"

In any case, thanks a lot for your efforts & I hope you'll be able to find a way to make it work again ^^"

**Comment by chris124567** [comment]
It could be related to https://github.com/chris124567/hulu/issues/10#issuecomment-1001839708 (Hulu now verifies user agent of the session).  I actually found a new key too.  I'll try to push the new key and a fix to allow people to set the user agent this week

**Comment by chris124567** [comment]
I go to test again and find out the key has been revoked :( Back to the drawing board I guess.

**Comment by costaht** [comment]
> It could be related to [#10 (comment)](https://github.com/chris124567/hulu/issues/10#issuecomment-1001839708) (Hulu now verifies user agent of the session). I actually found a new key too. I'll try to push the new key and a fix to allow people to set the user agent this week

Is that how they determine the resolution (user-agent)? Because when this wonderful piece of software was working, it was only possible to download 720p. I'll let you know if I get my hands on a new key.

**Comment by John1128** [comment]
@costaht What determines the resolution mainly is this values

https://github.com/chris124567/hulu/blob/master/client/types.go#L9-L16

If you got these values for an android device that Hulu plays on it in 1080p (like FireTV4K) Hulu Downloader might be modified to get the links in 1080p, at least this how it happens in the private script I use for downloading the video in 1080p from Hulu by getting only the links of the videos from the mpd of the android device and license, PSSH and the audio links from chrome (the mpd of the android device did not have the PSSH value).

**Comment by joshuachris2001** [comment]
bump

**Comment by chris124567** [comment]
> this still seems to be an issue

Please refer to the README: 

Notice
Widevine is currently revoking a lot of keys. This program won't work unless you have your own Widevine key and device information (I do not have any working keys).

See https://github.com/chris124567/hulu/issues/14#issuecomment-1064728748 for more info.
