### ISSUE TITLE
HULU_SESSION

### ISSUE THREAD

**Issue by jameshoyt** [chris124567/hulu#12]
I'm sorry for being an idiot if this is an easy fix but I have not been able to figure out the HULU_SESSION variable on Windows. I saw there was a previous issue that someone opened and you said you don't use Windows so you may not have an answer though.

Whenever I run the following, HULU_SESSION="xyz" hulu search -query="Test", I get that the HULU_SESSION is not an external or internal command. In the previous issue you mentioned using SET to set the HULU_SESSION variable but when I do that and run just, hulu search -query="Test", I get a message saying "It is necessary to specify the HULU_SESSION environment variable because the Hulu API requires this for all requests."

Thank you for any help.

**Comment by jkmartindale** [comment]
I've been doing this in PowerShell by first running
```powershell
$env:HULU_SESSION = "wow this is very long"
```
and then everything's good until I close the terminal window

**Comment by jameshoyt** [comment]
That worked perfectly, I'm still a bit of a newbie with Powershell.

Thankyou.
