### ISSUE TITLE
privateKey should be []byte

### ISSUE THREAD

**Issue by 89z** [chris124567/hulu#15]
https://github.com/chris124567/hulu/blob/8c095fc96aa9a03dd1eb5c6a6971b7580eede2ea/widevine/cdm.go#L37-L39

Currently its a string, that gets immediately cast to a `[]byte`. I think it would make sense if the function just called for a byte slice directly. That way, if someone is reading the key from a file `device_private_key`, its going to be a byte slice as well

**Comment by chris124567** [comment]
https://github.com/chris124567/hulu/commit/9bcd331a50d1f100cbf151ec67aa8937e102e981
