### ISSUE TITLE
Tutorial pls

### ISSUE THREAD

**Issue by xicobiu** [chris124567/hulu#18]
Tutorial to run the code, please!

go run main.go -HULU_SESSION="91UNUN7K600%2FO347dEU0oqHpL8RnBjicf" hulu search -query="m*a*s*h"
# command-line-arguments
.\main.go:70:17: undefined: client.NewDefaultClient

**Comment by chris124567** [comment]
Read the README.

"Widevine code has been deleted in response to a takedown request. The Hulu API package still functions."

You may have to find a copy of the code that was in this repository somewhere else.
