### ISSUE TITLE
panic: proto: cannot parse invalid wire-format data

### ISSUE THREAD

**Issue by num421337** [chris124567/hulu#19]
I get this error when trying to run a download, everything else so far has worked

panic: proto: cannot parse invalid wire-format data

goroutine 1 [running]:
main.main()
        C:/Users/num42/go/pkg/mod/github.com/chris124567/hulu@v0.0.0-20220610042858-77b6b192bc6e/main.go:172 +0x16e5

**Comment by jkmartindale** [comment]
You need up to date Widevine keys that aren't revoked (which are hard to come by). If you search this repository's issues for "cannot parse invalid wire-format data" you'll find some additional discussion in #10 and #11 for some steps on how to add keys that you get elsewhere.

**Comment by num421337** [comment]
if you're talking about the cdm files (client_id.bin. private_key.pem) I do have that, I'm just not sure how to use them with this, I tried looking at those discussions and I still can't quite figure it out

**Comment by num421337** [comment]
I tried converting the client id into a string of bytes and pasting that in place in the consts.go file and that changed nothing

**Comment by chris124567** [comment]
Either post the key/client id here or email it to chrisjtarry@gmail.com and I will try to give you some assistance.

**Comment by num421337** [comment]
Sent an email

**Comment by chris124567** [comment]
Resolved.  The problem was they did not properly update consts.go with their key / client ID information.
