### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Mavrick007** [chris124567/hulu#2]
i read the read me page how do i get it to work??

**Comment by chris124567** [comment]
1) Install `yt-dlp` and `mp4decrypt` using the links [here](https://github.com/chris124567/hulu#prerequisites)
2) Get your Hulu session cookie with the instructions in the [README](https://github.com/chris124567/hulu#retrieving-hulu-session-cookie) and save it somewhere
3) Figure out what movie or episode you want
4) Follow the instructions [here](https://github.com/chris124567/hulu#demonstration) (replacing the value of HULU_SESSION with the value you got from your web browser)

**Comment by Mavrick007** [comment]
still dont get it

**Comment by chris124567** [comment]
Would you mind being a little more specific

**Comment by Mavrick007** [comment]
yes, i have main.exe built now what?

**Comment by Mavrick007** [comment]
where do i add cookies to?

**Comment by chris124567** [comment]
to search "test" you can run
`HULU_SESSION="your cookie here" hulu search -query=test`

to get a list of episodes for a season of a show
`HULU_SESSION="your cookie here" hulu season -id="shows id number found from searching" -number=1`

to download a given episode or movie
 `HULU_SESSION="your cookie here" hulu download -id="id"`

Examples of all of these commands are given in the README

**Comment by Mavrick007** [comment]
> to search "test" you can run `HULU_SESSION="your cookie here" hulu search -query=test`
> 
> to get a list of episodes for a season of a show `HULU_SESSION="your cookie here" hulu season -id="shows id number found from searching" -number=1`
> 
> to download a given episode or movie `HULU_SESSION="your cookie here" hulu download -id="id"`
> 
> Examples of all of these commands are given in the README

'HULU_SESSION' is not recognized as an internal or external command,
operable program or batch file.

**Comment by chris124567** [comment]
That's cause you're using Windows.  I don't use Windows but I think you'd do something like that:
 
    set HULU_SESSION="abc"

Then just run the commands without `HULU_SESSION` in front.

**Comment by Mavrick007** [comment]
> 

tried that dont do anything

**Comment by chris124567** [comment]
I don't mean to be presumptuous but your questions and vague follow ups suggest that you have not put even the slightest modicum of effort into attempting to use this software and evidently you seem to be the only one with all of these problems
