### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ggtylerr** [chris124567/hulu#21]
![image](https://user-images.githubusercontent.com/28498877/221386916-4e86df6c-9203-4269-ae8b-bec7f39c255a.png)

**Comment by chris124567** [comment]
Yes, that code was removed and if you read the README and project description you can find out why.

**Comment by ggtylerr** [comment]
Yes, I know. But for whatever reason go is still trying to find and download it.

**Comment by chris124567** [comment]
Try cloning the repository?

**Comment by ggtylerr** [comment]
Results in a similar error:
![image](https://user-images.githubusercontent.com/28498877/221703308-57e3c45c-6e20-4a4e-bd99-2df9d5b3f2c0.png)

**Comment by chris124567** [comment]
Clone repository, change directory to repository, add missing files,  run `go build .`.  Works here.
