### ISSUE TITLE
Movies no longer work -eabID issue

### ISSUE THREAD

**Issue by eac4** [chris124567/hulu#8]
Downloading a movie: `panic: Get "": unsupported protocol scheme ""`

All good with TV.

Seems that because Hulu changed something on their end, eabID for movies is no longer obtained correctly for movies, eg

Response body of PlaybackInformation with movie
```{"_type":"deep_link_playback","browse":{"target_type":"movie","target_id":"f82b95f5-13da-4acd-b378-7d3f6864919f","target_theme":"hub_theme_entity_detail","params":{},"type":"browse"},"href":"https://discover.hulu.com/content/v5/hubs/movie/f82b95f5-13da-4acd-b378-7d3f6864919f?schema=1","id":"f82b95f5-13da-4acd-b378-7d3f6864919f","href_type":"movie","restriction_level":"not_rated"}```

With TV
```{"_type":"deep_link_playback","browse":{"target_type":"series","target_id":"227de06a-d3d4-42e0-9df1-bb5495e1738d","target_theme":"hub_theme_entity_detail","params":{},"type":"browse"},"eab_id":"EAB::48ccc382-71f4-49cb-9f37-394311790a9b::151224174::150327995","href":"https://discover.hulu.com/content/v5/hubs/series/227de06a-d3d4-42e0-9df1-bb5495e1738d?schema=1","id":"48ccc382-71f4-49cb-9f37-394311790a9b","href_type":"series","restriction_level":"not_rated"}```

**Comment by chris124567** [comment]
Everything should work now.  Make a new issue if there are any problems.
